trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: echo 'Building the project...'
      displayName: 'Build'
    # Add your build steps here

- stage: Test
  jobs:
  - job: Test
    steps:
    - script: echo 'Running tests...'
      displayName: 'Test'
    # Add your test steps here

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: echo 'Deploying the application...'
      displayName: 'Deploy'
    # Add your deployment steps here